---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks: 
    - name: Copy WAR file to Tomcat
      copy:
        src: "src: target/2023maven-webappwith-ansible.war"
        dest: "/opt/tomcat/webapps/2023MavenWebAppPipelineWithAnsible.war"
        remote_src: no
        
    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
